Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pyoptinterface as poi
from pyoptinterface import highs

model = highs.Model()

I = range(10)
J = range(20)

x = poi.make_tupledict(I, J, rule=lambda i, j: model.add_variable(lb=0, name=f"x({i},{j})"))

def constraint_rule(j):
    expr = poi.quicksum(x.select("*", j))
    con = model.add_linear_constraint(expr, poi.ConstraintSense.Equal, 1, name=f"con_{j}")
    return con

constraint = poi.make_tupledict(J, rule=constraint_rule)

obj = poi.quicksum(x.values(), lambda x: x*x)
model.set_objective(obj, poi.ObjectiveSense.Minimize)

model.optimize()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
Cell [0;32mIn[7], line 4[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpyoptinterface[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpoi[39;00m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpyoptinterface[39;00m [38;5;28;01mimport[39;00m highs
[0;32m----> 4[0m model [38;5;241m=[39m [43mhighs[49m[38;5;241;43m.[39;49m[43mModel[49m[43m([49m[43m)[49m
[1;32m      6[0m I [38;5;241m=[39m [38;5;28mrange[39m([38;5;241m10[39m)
[1;32m      7[0m J [38;5;241m=[39m [38;5;28mrange[39m([38;5;241m20[39m)

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pyoptinterface/_src/highs.py:286[0m, in [0;36mModel.__init__[0;34m(self)[0m
[1;32m    285[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m):
[0;32m--> 286[0m     [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[38;5;21;43m__init__[39;49m[43m([49m[43m)[49m
[1;32m    288[0m     [38;5;28mself[39m[38;5;241m.[39mmip_start_values: [38;5;28mdict[39m[VariableIndex, [38;5;28mfloat[39m] [38;5;241m=[39m [38;5;28mdict[39m()
[1;32m    290[0m     [38;5;28mself[39m[38;5;241m.[39madd_variables [38;5;241m=[39m types[38;5;241m.[39mMethodType(make_nd_variable, [38;5;28mself[39m)

[0;31mRuntimeError[0m: HiGHS library is not loaded

